-- OBSOLETE: This migration added MistServer challenge/hash columns.
-- MistServer has been replaced by Flussonic Media Server.
-- These columns were removed in: modify_stream_servers_for_flussonic.sql
-- This file is kept for historical reference only — do NOT run it.
